server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /decision { proxy_pass http://app:8000; }
    location /cases     { proxy_pass http://app:8000; }
    location /trace     { proxy_pass http://app:8000; }
    location /metrics   { proxy_pass http://app:8000; }
    location /health    { proxy_pass http://app:8000; }

    location / {
        try_files $uri /index.html;
    }
}